[package]
name = "dsh-types"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
libc.workspace=true
nix.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
cfg-if.workspace = true
